# [XOR]
# https://leetcode.com/problems/find-the-difference/
# 389. Find the Difference

# History:
# Google
# 1.
# Mar 10, 2020

# Given two strings s and t which consist of only lowercase letters.
#
# String t is generated by random shuffling string s and then add one more letter at a random
# position.
#
# Find the letter that was added in t.
#
# Example:
#
# Input:
# s = "abcd"
# t = "abcde"
#
# Output:
# e
#
# Explanation:
# 'e' is the letter that was added.


class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        ret = 0

        for n in t:
            ret ^= ord(n)

        for n in s:
            ret ^= ord(n)

        return chr(ret)
